services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
     - "9090:9090"
    restart: unless-stopped
    networks:
      - monitoring

  victorialogs:
    image: victoriametrics/victoria-logs:latest-scratch
    container_name: victoria-logs
    ports:
      - "9428:9428"
    command: >
      -retentionPeriod=3d
      -storageDataPath=/vlogs-data
    volumes:
      - victoria-logs-data:/vlogs-data
    restart: unless-stopped
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    build: ./grafana
    container_name: grafana
    expose:
     - "3000"
    depends_on:
      - prometheus
      - victorialogs
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_LOG_LEVEL=debug
    networks:
      - monitoring

  haproxy:
    image: haproxy:latest
    container_name: haproxy
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "80:80"
    depends_on:
      - grafana
      - victorialogs
    networks:
      - monitoring

volumes:
  grafana-storage:
  victoria-logs-data:

networks:
  monitoring:
    driver: bridge
